### ISSUE TITLE
Menu Roadmap

### ISSUE THREAD

**Issue by Anahkiasen** [vespakoen/menu#19]
# Menu roadmap

- [x] Add **Link** and **Raw** classes to better handle content
- [ ] Finish code clean-up
- [x] Rename repository to just `menu` as the package's been agnostic for a while
- [ ] Allow chaining of attributes and classes

**Comment by vespakoen** [comment]
Is this issue still relevant or can it be closed?

P.S. I haven't been using PHP in quite some time (my system doesn't even have it installed at the moment) and haven't been using Laravel > 4.

I would love to focus my attention to other projects, so if anyone is interested in becoming a maintainer of this package, I'd love to hear it!
